export enum QuestionType {
    MC = 'MC',
    DRAG_DROP = 'DRAG_DROP',
    SELECTION = 'SELECTION',
    INPUT_FIELD='INPUT_FIELD',
    FEEDBACK='FEEDBACK',
    SLIDER='SLIDER',
    MEMORY='MEMORY',
    TIMER='TIMER',
    ALARM='ALARM',
    ALARM_DRAG_DROP='ALARM_DRAG_DROP',
    SELECTION_2='SELECTION_2',
    LESEN='LESEN',
    DRAG_DROP_2 = 'DRAG_DROP_2'

}