
export enum QuestionCategory {
    QUIZ= 'QUIZ',
    COMIC = 'COMIC',
    AUSFUELLEN = 'AUSFUELLEN',
    ERINNERUNGALARM = 'ERINNERUNGALARM',
    ZUZUORDNEN1 = 'ZUZUORDNEN1',
    ZUZUORDNEN2 = ' ZUZUORDNEN2',
    QUESTION='QUESTION',
    MEMORY='MEMORY',
    SELBSTDARSTELLUNGONLINE='SELBSTDARSTELLUNGONLINE',
    UEBUNGMITTIMER='UEBUNGMITTIMER',
    GENUSSMOMENTE='GENUSSMOMENTE',
    KOGNITIONEN='KOGNITIONEN',
    SOZIALEUNTERSTUETZUNG='SOZIALEUNTERSTUETZUNG',
    ERKENNENVONUMGANGMITEMOTIONEN='ERKENNENVONUMGANGMITEMOTIONEN'



}